# This is a basic workflow to help you get started with Actions

name: Deploy

on: [push]

jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use node.js version ${{ matrix.node-version }}
        uses: action/setup-node@v1
        with:
            node-version: ${{ matrix.node-version }}
        
      - name: Installing Dependencies
        run: npm install

      - name: Running
        run: npm start
